services:
  - type: web
    name: blox-fruits-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        scope: build,runtime
